[package]
name = "windy-grid"
version = "0.1.0"
authors = ["critiqjo <john.ch.fr@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"

[dependencies.coio]
git = "https://github.com/zonyitoo/coio-rs.git"
